services:
  mock:
    build:
      context: ./mock
    ports:
      - "12004:12004"
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - ARGOCD_URL=http://mock:12004
      - SPRING_PROFILES_ACTIVE=no-db
    ports:
      - "8080:8080"
    depends_on:
      - mock
    restart: unless-stopped

  portal:
    build:
      context: ./portal
      dockerfile: Dockerfile
      args:
        - VITE_ARGOCD_UI_URL=http://localhost:12004
        - VITE_TEAMS_CHAT_URL=https://example.com
    ports:
      - "80:80"
    depends_on:
      - mock
      - server
    restart: unless-stopped
