services:
  db:
    image: postgres:16-alpine
    container_name: kubiverse-portal-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: kubiverse-portal
    ports:
      - "12002:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: kubiverse-portal-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "12003:80"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  pgdata:
