server:
  port: 12001

spring:
  application:
    name: Kubiverse Portal
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:no-db}
  datasource:
    url: jdbc:postgresql://localhost:12002/kubiverse-portal
    username: root
    password: rootpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: aVeryStrongSecretKeyThatShouldBeAtLeastThirtyTwoBytesLongForHS256
  expiration: 86400000 # 24 hours

argocd:
  url: ${ARGOCD_URL:http://localhost:12004}
  api-key: ${ARGOCD_API_KEY:mock-token}

---
spring:
  config:
    activate:
      on-profile: "no-db"
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
